packages:
  - "modules/backend"
  - "modules/frontend"
  - "modules/domain"
  - "modules/libraries/assert"
  - "modules/libraries/config"
  - "modules/libraries/functions"
  - "modules/libraries/logger"
  - "modules/libraries/state-manager"
