services:
  db:
    image: postgres
    shm_size: 128mb
    volumes:
     - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
